#!/usr/bin/env python3
"""Build task-asset thumbnails for the Task Browser.

Reads `static/js/task_data.js`, finds every task with `input_assets`, resolves
each asset's source image, resizes/converts to WebP, writes it under
`static/images/task-assets/<task-id>/<basename>.webp`, and rewrites
`task_data.js` with a `web_path` field added to each asset entry.

Source images live in the sibling HarnessAudit repo:
    /home/cliu322/HarnessAudit/<task.source_path parent>/<asset.path>

Usage:
    python3 scripts/build_task_assets.py
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

from PIL import Image

SITE_ROOT = Path(__file__).resolve().parent.parent
SOURCE_ROOT = Path("/home/cliu322/HarnessAudit")
DATA_JS = SITE_ROOT / "static/js/task_data.js"
OUT_DIR = SITE_ROOT / "static/images/task-assets"

MAX_WIDTH = 1024            # cap longest dim (large dim)
MAX_HEIGHT = 1024
QUALITY = 82                # WebP quality
TARGET_EXT = ".webp"


def load_data() -> tuple[str, str, dict]:
    text = DATA_JS.read_text()
    m = re.search(r"^(window\.HA_TASK_BROWSER_DATA\s*=\s*)(\{.*\});?\s*$",
                  text, re.DOTALL | re.MULTILINE)
    if not m:
        raise SystemExit("Could not find data assignment in task_data.js")
    prefix, payload = m.group(1), m.group(2)
    return prefix, text, json.loads(payload)


def resize_and_save(src: Path, dst: Path) -> tuple[int, int, int]:
    """Resize image keeping aspect ratio, save as WebP. Returns (w, h, bytes)."""
    img = Image.open(src)
    if img.mode in ("RGBA", "P"):
        img = img.convert("RGBA")
    else:
        img = img.convert("RGB")
    img.thumbnail((MAX_WIDTH, MAX_HEIGHT), Image.LANCZOS)
    dst.parent.mkdir(parents=True, exist_ok=True)
    save_kwargs = {"quality": QUALITY, "method": 6}
    img.save(dst, "WEBP", **save_kwargs)
    return img.width, img.height, dst.stat().st_size


def sanitize_basename(p: str) -> str:
    stem = Path(p).stem
    # normalize non-ascii / spaces just in case
    stem = re.sub(r"[^A-Za-z0-9._-]+", "_", stem)
    return stem + TARGET_EXT


def main() -> int:
    prefix, _, data = load_data()

    if OUT_DIR.exists():
        # wipe stale to avoid orphans
        for old in OUT_DIR.rglob("*"):
            if old.is_file():
                old.unlink()
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    tasks = data.get("tasks", [])
    n_assets = 0
    n_failed = 0
    total_in_bytes = 0
    total_out_bytes = 0

    for task in tasks:
        assets = task.get("input_assets") or []
        if not assets:
            continue
        task_id = task["id"]
        # task.source_path is repo-relative, e.g. "multi_agent/tasks/finance/insurance/fin-t13.yaml"
        yaml_rel = Path(task.get("source_path", ""))
        task_dir = SOURCE_ROOT / yaml_rel.parent

        for asset in assets:
            asset_type = asset.get("asset_type")
            rel_path = asset.get("path")
            if asset_type != "image" or not rel_path:
                continue
            src = task_dir / rel_path
            if not src.is_file():
                print(f"  [MISS] {task_id} → {src}", file=sys.stderr)
                n_failed += 1
                continue

            web_name = sanitize_basename(rel_path)
            dst = OUT_DIR / task_id / web_name

            try:
                w, h, out_bytes = resize_and_save(src, dst)
            except Exception as exc:
                print(f"  [ERR ] {task_id}/{web_name}: {exc}", file=sys.stderr)
                n_failed += 1
                continue

            asset["web_path"] = f"static/images/task-assets/{task_id}/{web_name}"
            asset["web_w"] = w
            asset["web_h"] = h
            n_assets += 1
            in_bytes = src.stat().st_size
            total_in_bytes += in_bytes
            total_out_bytes += out_bytes
            print(f"  {task_id}/{web_name}  {w}×{h}  "
                  f"{in_bytes//1024}KB → {out_bytes//1024}KB "
                  f"({out_bytes/in_bytes*100:.1f}%)")

    # Rewrite task_data.js with updated assets
    new_payload = json.dumps(data, ensure_ascii=False, indent=2)
    new_text = f"// Generated by scripts/build_task_browser_data.py and scripts/build_task_assets.py. Do not edit manually.\n{prefix}{new_payload};\n"
    DATA_JS.write_text(new_text)

    print(f"\nDone.")
    print(f"  Processed assets: {n_assets}")
    print(f"  Failed:           {n_failed}")
    print(f"  Source bytes:     {total_in_bytes/1024/1024:.1f} MB")
    print(f"  Output bytes:     {total_out_bytes/1024/1024:.1f} MB")
    print(f"  Compression:      {total_out_bytes/max(1,total_in_bytes)*100:.1f}%")
    print(f"  Output dir:       {OUT_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
